"""
================================================================================
  Aggregated Results Analysis & Visualisation Suite
================================================================================

This module parses the output directories generated by the structural refinement
workflow. It aggregates statistical metrics, including the refinement residual 
(Rw), lattice parameters, structural bonding forensics, 
and specifically targeted refinement variables. It subsequently generates a 
suite of visualisations to assess structural evolution across 
a data series (e.g., a temperature series).

Authors: 
	- Tomasz Stawski (tomasz.stawski@bam.de, tomasz.stawski@gmail.com)
	- Aiste Miliute (aiste.miliute@bam.de)
	- Joana Bustamante (joana.bustamante@bam.de)
Version: 1.3.0
License: MIT License
"""

import os
import re
import glob
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from diffpy.Structure import loadStructure
from itertools import combinations
import concurrent.futures
from pymatgen.util.coord import get_angle
from pymatgen.core import Structure

# Core infrastructure and specific configuration imports
from pdf_refinement_core import StructureAnalyzer, RefinementConfig
from pdf_execution import project_config

# =============================================================================
# Helper Wrappers for Forensics (Standalone Compatibility)
# =============================================================================

class _ForensicsMockParam:
    """Mock parameter class designed to mimic diffpy parameter objects."""
    def __init__(self, value):
        self.value = value

class _ForensicsMockLattice:
    """Mock lattice class structured to interface seamlessly with StructureAnalyzer."""
    def __init__(self, lat):
        self.a = _ForensicsMockParam(lat.a)
        self.b = _ForensicsMockParam(lat.b)
        self.c = _ForensicsMockParam(lat.c)
        self.alpha = _ForensicsMockParam(lat.alpha)
        self.beta = _ForensicsMockParam(lat.beta)
        self.gamma = _ForensicsMockParam(lat.gamma)

class _ForensicsMockAtom:
    """Mock atom class providing necessary attributes for bond calculation."""
    def __init__(self, atom):
        self.name = getattr(atom, 'name', atom.label)
        self.element = atom.element
        self.label = atom.label
        self.x = _ForensicsMockParam(atom.x)
        self.y = _ForensicsMockParam(atom.y)
        self.z = _ForensicsMockParam(atom.z)

class _ForensicsWrapper:
    """
    Wrapper structure mapping a diffpy Structure object into a format natively
    compatible with the core StructureAnalyzer algorithms.
    """
    def __init__(self, structure):
        self.lattice = _ForensicsMockLattice(structure.lattice)
        self.scatterers = [_ForensicsMockAtom(a) for a in structure]
        self.phase = self 
        
    def getScatterers(self):
        """Returns the list of mock scatterer objects."""
        return self.scatterers

class GeometricBondAnalyzer:
    """
    Analyses geometric structural properties, including bond distances, angles,
    and transversal displacements, from CIF structural models utilising the pymatgen library.
    
    Transversal displacement (U_tra) measures the orthogonal distance of a central 
    bridging atom (e.g., oxygen) away from the linear axis connecting its two 
    adjacent metal neighbours. It effectively quantifies the degree of non-linearity 
    or "buckling" within an atomic linkage.
    
    Derived from the original experimental bond analysis workflow by Joana Bustamante.
    """
    def __init__(self, rcut=2.5):
        """
        Initialises the GeometricBondAnalyzer.
        
        Args:
            rcut (float): The maximum cutoff radius (in Ångströms) for identifying adjacent atomic neighbours.
        """
        self.rcut = rcut

    def extract_angles(self, cif_path, center_species, neigh1, neigh2):
        """
        Extracts bond lengths and corresponding angles for a specified atomic triad within the structure.
        
        Args:
            cif_path (str): The file pathway to the target CIF structural model.
            center_species (str): The elemental symbol of the central atom within the triad.
            neigh1 (str): The elemental symbol of the first neighbouring atom.
            neigh2 (str): The elemental symbol of the second neighbouring atom.
            
        Returns:
            dict: A dictionary containing arrays of the first bond lengths ('D1'), 
                  the second bond lengths ('D2'), and the subtended angles ('Angle').
        """
        d1 = []
        d2 = []
        angles = []
        try:
            import warnings
            with warnings.catch_warnings():
                warnings.simplefilter("ignore")
                struc = Structure.from_file(cif_path)
        except Exception as e:
            print(f"[WARN] GeometricBondAnalyzer failed to load {cif_path}: {e}")
            return {'D1': d1, 'D2': d2, 'Angle': angles}

        center_indices = [i for i, site in enumerate(struc.sites) if site.species_string == center_species]
        
        for ix in center_indices:
            center_site = struc[ix]
            neighbors = struc.get_neighbors(center_site, self.rcut)
            neighbors = [n for n in neighbors if n.species_string in (neigh1, neigh2)]
            
            for j, k in combinations(neighbors, 2):
                if ((j.species_string == neigh1 and k.species_string == neigh2) or
                    (j.species_string == neigh2 and k.species_string == neigh1)):
        
                    vec1 = j.coords - center_site.coords
                    vec2 = k.coords - center_site.coords
                   
                    d1.append(np.linalg.norm(vec1))
                    d2.append(np.linalg.norm(vec2))
                    angles.append(get_angle(vec1, vec2))

        return {'D1': d1, 'D2': d2, 'Angle': angles}

    def calculate_transversal_displacement(self, d1_array, d2_array, angle_array):
        """
        Computes the transversal displacement (U_tra) of the central bridging atom. 
        This parameter represents the perpendicular offset (buckling) of the central atom 
        relative to the direct vector connecting its two adjacent neighbours, utilising 
        trigonometric principles (Law of Cosines and Sines).
        
        Args:
            d1_array (list or np.ndarray): An array of the first bond distances.
            d2_array (list or np.ndarray): An array of the second bond distances.
            angle_array (list or np.ndarray): An array of the internal angles (in degrees) 
                                              subtended by the two bonds.
            
        Returns:
            np.ndarray: An array containing the calculated transversal displacements in Ångströms.
        """
        if not d1_array:
            return np.array([])
            
        d1 = np.array(d1_array)
        d2 = np.array(d2_array)
        ang = np.array(angle_array) * np.pi / 180  # radians

        c = np.sqrt(d1**2 + d2**2 - 2 * d1 * d2 * np.cos(ang))
        with np.errstate(divide='ignore', invalid='ignore'):
            sin_term = (d1 * np.sin(ang)) / c
            sin_term = np.clip(sin_term, -1.0, 1.0)
            B = np.arcsin(sin_term) * 180 / np.pi
            theta = 180 - np.array(angle_array) - B

        u_tra = d2 * np.sin(theta * np.pi / 180)
        return u_tra

    def process_structure(self, cif_path):
        """
        Executes a comprehensive geometric analysis of a given structural model, 
        evaluating predefined atomic triads to determine bond angles and transversal 
        displacements.
        
        Args:
            cif_path (str): The file pathway to the target CIF structural model.
            
        Returns:
            tuple: A tuple containing two dictionaries. The first dictionary holds the 
                   extracted geometric data for each triad. The second dictionary contains 
                   the calculated transversal displacement statistics for relevant bonds.
        """
        triads = [
            ("V", "O", "O", "O-V-O"),
            ("Zr", "O", "O", "O-Zr-O"),
            ("O", "V", "V", "V-O-V"),
            ("O", "Zr", "V", "Zr-O-V")
        ]
        
        results = {}
        for center, n1, n2, name in triads:
            results[name] = self.extract_angles(cif_path, center, n1, n2)
            
        u_tra_results = {}
        for mom_bond in ["V-O-V", "Zr-O-V"]:
            if mom_bond in results and len(results[mom_bond]['Angle']) > 0:
                u_tra = self.calculate_transversal_displacement(
                    results[mom_bond]['D1'],
                    results[mom_bond]['D2'],
                    results[mom_bond]['Angle']
                )
                u_tra_results[mom_bond] = {
                    'U_tra_mean': float(np.nanmean(u_tra)) if u_tra.size > 0 else np.nan,
                    'U_tra_values': u_tra
                }
            else:
                u_tra_results[mom_bond] = {
                    'U_tra_mean': np.nan,
                    'U_tra_values': np.array([])
                }
                
        return results, u_tra_results

# =============================================================================
# Primary Analysis Aggregator
# =============================================================================

class ResultsAggregator:
    """
    Aggregates analytical results and structural parameters from multiple 
    refinement directories. Facilitates the extraction, compilation, and 
    visualisation of sequential refinement trends.
    """
    
    def __init__(self, fit_root_dir, config_dict):
        """
        Initialises the ResultsAggregator.
        
        Args:
            fit_root_dir (str): The primary directory pathway containing the 
                                sequential refinement dataset subdirectories.
            config_dict (dict): The central project configuration dictionary.
        """
        self.root_dir = fit_root_dir
        self.config = RefinementConfig(config_dict)
        self.analyzer = StructureAnalyzer(self.config.detailed_composition)
        self.bond_analyzer = GeometricBondAnalyzer(rcut=2.5)
        
        self.summary_data = []
        self.rw_histories = {} # Dictionary mapping temperature to its corresponding DataFrame
        self.detailed_forensics_data = [] # List storing dictionaries of individual bond parameters
        self.utra_distributions = {'V-O-V': {}, 'Zr-O-V': {}} # Stores transversal displacement arrays for KDE generation
        self.angle_distributions = {'O-V-O': {}, 'O-Zr-O': {}, 'V-O-V': {}, 'Zr-O-V': {}} # Stores bond angle arrays for KDE generation
        
        # Defining the targeted subset of refinement parameters for explicit extraction
        self.target_params = [
            'Uiso_O_Phase0', 'Uiso_V_Phase0', 'Uiso_Zr_Phase0',
            'delta2_Phase0', 'psize_Phase0', 's_Phase0'
        ]

    def parse_temperature(self, folder_name):
        """
        Extracts the numeric temperature value from a formatted directory string.
        
        Args:
            folder_name (str): The name of the dataset subdirectory.
            
        Returns:
            int or None: The extracted temperature integer, or None if unmatched.
        """
        match = re.search(r'_(\d+)C_', folder_name)
        if match:
            return int(match.group(1))
        return None

    def scan_and_extract(self):
        """
        Systematically scans the target directory to parse subdirectories and 
        extract refinement quality metrics (Rw), lattice dimensions, specific 
        refinement parameters, and structural bonding forensics.
        """
        print(f"[INFO] Scanning refinement results within: {self.root_dir}")
        
        try:
            subdirs = sorted([d for d in os.listdir(self.root_dir) 
                              if os.path.isdir(os.path.join(self.root_dir, d))])
        except FileNotFoundError:
            print(f"[ERROR] The specified directory pathway was not found: {self.root_dir}")
            return

        with concurrent.futures.ProcessPoolExecutor() as executor:
            results = list(executor.map(self._process_single_folder, subdirs))

        for res in results:
            if res is None:
                continue
                
            temp, record, history_df, forensics_list, utra_data_out, angle_data_out = res
            
            self.summary_data.append(record)
            if not history_df.empty:
                self.rw_histories[temp] = history_df
            self.detailed_forensics_data.extend(forensics_list)
            
            if utra_data_out['V-O-V'] is not None:
                self.utra_distributions['V-O-V'][temp] = utra_data_out['V-O-V']
            if utra_data_out['Zr-O-V'] is not None:
                self.utra_distributions['Zr-O-V'][temp] = utra_data_out['Zr-O-V']
                
            for triad, angles in angle_data_out.items():
                if angles is not None:
                    self.angle_distributions[triad][temp] = angles
                    
            print(f"  > Processed Sequence {temp}°C | Final Rw: {record['Final_Rw']:.4f} | Lattice a: {record['a']:.3f}")

    def _process_single_folder(self, folder):
        """
        Worker function to process a single temperature dataset directory.
        Returns aggregated structural and parameter records to be integrated.
        """
        temp = self.parse_temperature(folder)
        if temp is None:
            return None
        
        full_path = os.path.join(self.root_dir, folder)
        
        # 1. Extract Refinement Residual (Rw) History
        history_df = self._stitch_rw_logs(full_path)
        final_rw = history_df['Rw'].iloc[-1] if not history_df.empty else np.nan

        # 2. Extract Structural Dimensions & Bonding Forensics
        cif_path = os.path.join(full_path, "Phase0_2.cif")
        structure_stats = {'a': np.nan, 'vol': np.nan, 'outlier_pct': 0}
        forensics_list = []
        utra_data_out = {'V-O-V': None, 'Zr-O-V': None}
        angle_data_out = {'O-V-O': None, 'O-Zr-O': None, 'V-O-V': None, 'Zr-O-V': None}
        
        if os.path.exists(cif_path):
            try:
                stru = loadStructure(cif_path)
                structure_stats['a'] = stru.lattice.a
                structure_stats['vol'] = stru.lattice.volume
                
                forensics_stats, forensics_list = self._run_forensics(cif_path, temp)
                structure_stats.update(forensics_stats)
                
                bond_data, utra_data = self.bond_analyzer.process_structure(cif_path)
                structure_stats['Mean_U_tra_V-O-V'] = utra_data['V-O-V']['U_tra_mean']
                structure_stats['Mean_U_tra_Zr-O-V'] = utra_data['Zr-O-V']['U_tra_mean']
                
                utra_data_out['V-O-V'] = utra_data['V-O-V']['U_tra_values']
                utra_data_out['Zr-O-V'] = utra_data['Zr-O-V']['U_tra_values']
                
                for triad in angle_data_out.keys():
                    if triad in bond_data:
                        angle_data_out[triad] = bond_data[triad]['Angle']
            except Exception as e:
                print(f"[WARN] Failed to parse the CIF model for {temp}°C. Error: {e}")

        # 3. Extract Specific Refinement Parameters
        summary_path = os.path.join(full_path, "fitting_summary_2.txt")
        param_stats = self._extract_params_from_summary(summary_path)

        # Compile standard record format
        record = {
            'Temperature': temp,
            'Path': full_path,
            'Final_Rw': final_rw,
            **structure_stats,
            **param_stats
        }
        
        return (temp, record, history_df, forensics_list, utra_data_out, angle_data_out)

    def _stitch_rw_logs(self, folder_path):
        """
        Aggregates sequential refinement residual logs to construct a continuous, 
        global iteration axis for tracking convergence.
        
        Args:
            folder_path (str): The specific subdirectory path containing the logs.
            
        Returns:
            pd.DataFrame: The aggregated history of the refinement sequence.
        """
        log_files = sorted(glob.glob(os.path.join(folder_path, "rw_log_*.csv")))
        dfs = []
        cumulative_iter = 0
        
        for log in log_files:
            try:
                df = pd.read_csv(log)
                df['Global_Iteration'] = df['Iteration'] + cumulative_iter
                dfs.append(df)
                if not df.empty:
                    cumulative_iter = df['Global_Iteration'].iloc[-1]
            except pd.errors.EmptyDataError:
                pass
            except Exception as e:
                print(f"[WARN] Encountered an error processing {log}: {e}")
                
        if dfs:
            return pd.concat(dfs, ignore_index=True)
        return pd.DataFrame()

    def _run_forensics(self, cif_path, temp):
        """
        Utilises the StructureAnalyzer to systematically identify anomalous bond 
        distances (outliers) and categorise their local connectivity topologies.
        
        Args:
            cif_path (str): The pathway to the relevant CIF structural model.
            temp (int): The associated dataset temperature.
            
        Returns:
            dict: Compiled summary statistics relating to bonding configurations.
        """
        wrapper = _ForensicsWrapper(loadStructure(cif_path))
        all_bonds = self.analyzer.get_polyhedral_bond_vectors(wrapper)
        
        oxygen_connectivity = {}
        for b_type, bonds in all_bonds.items():
            if 'O-O' in b_type:
                continue 
            for bond in bonds:
                o_idx = bond['atom2']['index']
                cation_sym = bond['central_atom']['symbol']
                oxygen_connectivity.setdefault(o_idx, []).append(cation_sym)

        def get_conn_type(bond):
            o_idx = bond['atom2']['index']
            vertex_sym = bond['atom2']['symbol']
            cats = oxygen_connectivity.get(o_idx, [])
            
            if not cats:
                return "Isolated"
                
            unique_cats = sorted(list(set(cats)))
            if len(cats) == 1:
                return f"Terminal ({cats[0]}-{vertex_sym})"
            elif len(unique_cats) == 1:
                return f"Bridge ({unique_cats[0]}-{vertex_sym}-{unique_cats[0]})"
            else:
                return f"Linker ({'-'.join(unique_cats)})"

        target_bonds = all_bonds.get('V-O', [])
        if not target_bonds:
            return {}, []
        
        total = len(target_bonds)
        outliers = [b for b in target_bonds if b['length'] > 1.80] 
        
        forensics_list = []
        for bond in target_bonds:
            forensics_list.append({
                'Temperature': temp,
                'Bond_Length': bond['length'],
                'Connectivity': get_conn_type(bond),
                'Is_Outlier': bond['length'] > 1.80
            })

        stats = {
            'VO_Total': total,
            'VO_Outliers': len(outliers),
            'VO_Outlier_Pct': (len(outliers) / total) * 100 if total else 0
        }
        return stats, forensics_list

    def _extract_params_from_summary(self, summary_path):
        """
        Parses the refinement summary text document to extract targeted variables 
        and their associated mathematical uncertainties.
        
        Args:
            summary_path (str): The pathway to the relevant summary text file.
            
        Returns:
            dict: The extracted parameters mapped to their values and errors.
        """
        extracted = {}
        for p in self.target_params:
            extracted[p] = np.nan
            extracted[f"{p}_err"] = np.nan

        if not os.path.exists(summary_path):
            return extracted

        try:
            with open(summary_path, 'r') as f:
                lines = f.readlines()
            
            for line in lines:
                parts = line.strip().split()
                if not parts:
                    continue
                
                param_name = parts[0]
                if param_name in self.target_params:
                    try:
                        extracted[param_name] = float(parts[1])
                        
                        if len(parts) >= 4 and parts[2] == '+/-':
                            extracted[f"{param_name}_err"] = float(parts[3])
                        else:
                            extracted[f"{param_name}_err"] = 0.0
                    except ValueError:
                        pass
        except Exception as e:
            print(f"[WARN] Error extracting parameters from {summary_path}. Error: {e}")
            
        return extracted

    # =============================================================================
    # VISUALISATION METHODS
    # =============================================================================
    
    def plot_overview(self, output_dir="analysis_plots"):
        """
        Generates a comprehensive suite of graphical summaries depicting the 
        extracted refinement data.
        
        Args:
            output_dir (str): The target directory for the generated visualisations.
        """
        if not os.path.exists(output_dir):
            os.makedirs(output_dir)
            
        df = pd.DataFrame(self.summary_data)
        
        if df.empty:
            print("[WARN] No analytical data was extracted for visualisation.")
            return
            
        df = df.sort_values('Temperature')

        # 1. Refinement Residual (Rw) vs Temperature
        plt.figure(figsize=(7, 5))
        sns.lineplot(data=df, x='Temperature', y='Final_Rw', marker='o', color='firebrick')
        plt.title("Final Fit Quality vs Temperature")
        plt.xlabel("Temperature (°C)")
        plt.ylabel("Rw")
        plt.grid(True, alpha=0.3)
        plt.savefig(os.path.join(output_dir, "1_Rw_vs_Temp.png"), dpi=300)
        plt.close()

        # 2. Lattice Parameter vs Temperature
        plt.figure(figsize=(7, 5))
        sns.lineplot(data=df, x='Temperature', y='a', marker='s', color='navy')
        plt.title("Lattice Parameter 'a' vs Temperature")
        plt.xlabel("Temperature (°C)")
        plt.ylabel("Lattice Constant a (Å)")
        plt.grid(True, alpha=0.3)
        plt.savefig(os.path.join(output_dir, "2_Lattice_vs_Temp.png"), dpi=300)
        plt.close()
        
        # 3. Structural Forensics: Bonding Anomalies vs Temperature
        plt.figure(figsize=(7, 5))
        sns.barplot(data=df, x='Temperature', y='VO_Outlier_Pct', color='teal')
        plt.title("Percentage of V-O Bond Outliers (> 1.8 Å)")
        plt.xlabel("Temperature (°C)")
        plt.ylabel("Outliers (%)")
        plt.xticks(rotation=45)
        plt.tight_layout()
        plt.savefig(os.path.join(output_dir, "3_Forensics_Outliers.png"), dpi=300)
        plt.close()

        # 3b. Mean Transversal Displacement vs Temperature
        if 'Mean_U_tra_V-O-V' in df.columns and 'Mean_U_tra_Zr-O-V' in df.columns:
            plt.figure(figsize=(7, 5))
            sns.lineplot(data=df, x='Temperature', y='Mean_U_tra_V-O-V', marker='o', label='V-O-V')
            sns.lineplot(data=df, x='Temperature', y='Mean_U_tra_Zr-O-V', marker='s', label='Zr-O-V')
            plt.title("Mean Transversal Displacement ($U_{tra}$) vs Temperature")
            plt.xlabel("Temperature (°C)")
            plt.ylabel("$U_{tra}$ (Å)")
            plt.legend()
            plt.grid(True, alpha=0.3)
            plt.savefig(os.path.join(output_dir, "3b_Utra_vs_Temp.png"), dpi=300)
            plt.close()

        # 3c. Full Transversal Displacement KDE Distributions
        self._plot_utra_distributions(output_dir)

        # 3d. Full Angle KDE Distributions
        self._plot_angle_distributions(output_dir)

        # 4. Refinement Residual Convergence Profile
        self._plot_convergence_history(output_dir)
        
        # 5. Detailed Bonding Forensics Distribution
        self._plot_forensics_evolution(output_dir)

        # 6. Specific Parameter Evolution Arrays
        self._plot_params_evolution(output_dir, df)
        
        # 7. Compile Final Analytical Dataframe
        df.to_csv(os.path.join(output_dir, "summary_table.csv"), index=False)
        
        # 8. Save Raw Distribution Data for Replotting
        self._save_distribution_data(output_dir)
        
        print(f"[INFO] Analytical compilation complete. Outputs saved securely within '{output_dir}/'.")

    def _save_distribution_data(self, output_dir):
        """
        Saves the raw array data for transversal displacements and bond angles 
        into CSV files to allow for external replotting.
        """
        for bond_type, dists in self.utra_distributions.items():
            if not dists: continue
            max_len = max([len(arr) for arr in dists.values()] + [0])
            padded_data = {}
            for temp in sorted(dists.keys()):
                arr = dists[temp]
                padded_arr = np.pad(arr, (0, max_len - len(arr)), constant_values=np.nan)
                padded_data[f"{temp}C"] = padded_arr
            pd.DataFrame(padded_data).to_csv(os.path.join(output_dir, f"7_Utra_Data_{bond_type}.csv"), index=False)

        for bond_type, dists in self.angle_distributions.items():
            if not dists: continue
            max_len = max([len(arr) for arr in dists.values()] + [0])
            padded_data = {}
            for temp in sorted(dists.keys()):
                arr = dists[temp]
                padded_arr = np.pad(arr, (0, max_len - len(arr)), constant_values=np.nan)
                padded_data[f"{temp}C"] = padded_arr
            pd.DataFrame(padded_data).to_csv(os.path.join(output_dir, f"8_Angle_Data_{bond_type}.csv"), index=False)

    def _plot_utra_distributions(self, output_dir):
        """
        Generates overlaid Kernel Density Estimate (KDE) distributions of the 
        transversal displacements across all temperatures, mapping the density evolution.
        """
        for bond_type, dists in self.utra_distributions.items():
            if not dists:
                continue
            
            plt.figure(figsize=(8, 6))
            temps = sorted(dists.keys())
            if not temps:
                continue
                
            norm = plt.Normalize(min(temps), max(temps))
            cmap = plt.cm.viridis_r
            
            for temp in temps:
                u_tra = dists[temp]
                if len(u_tra) > 0:
                    sns.kdeplot(u_tra, fill=True, color=cmap(norm(temp)), alpha=0.3, linewidth=1.5)
            
            sm = plt.cm.ScalarMappable(cmap=cmap, norm=norm)
            sm.set_array([])
            cbar = plt.colorbar(sm, ax=plt.gca())
            cbar.set_label('Temperature (°C)')
            
            plt.xlabel(rf"U$_{{tra}}$ ($\AA$)", fontsize=14)
            plt.ylabel("Density", fontsize=14)
            plt.tick_params(axis='both', labelsize=12, length=6, width=1.5)
            plt.title(f"Transversal Displacement ($U_{{tra}}$) Density - {bond_type}")
            plt.tight_layout()
            plt.savefig(os.path.join(output_dir, f"7_Utra_Distribution_{bond_type}.png"), dpi=300)
            plt.close()

    def _plot_angle_distributions(self, output_dir):
        """
        Generates overlaid Kernel Density Estimate (KDE) distributions of the 
        bond angles across all temperatures.
        """
        for bond_type, dists in self.angle_distributions.items():
            if not dists:
                continue
            
            plt.figure(figsize=(8, 6))
            temps = sorted(dists.keys())
            if not temps:
                continue
                
            norm = plt.Normalize(min(temps), max(temps))
            cmap = plt.cm.viridis_r
            
            for temp in temps:
                angles = dists[temp]
                if len(angles) > 0:
                    sns.kdeplot(angles, fill=True, color=cmap(norm(temp)), alpha=0.3, linewidth=1.5)
            
            sm = plt.cm.ScalarMappable(cmap=cmap, norm=norm)
            sm.set_array([])
            cbar = plt.colorbar(sm, ax=plt.gca())
            cbar.set_label('Temperature (°C)')
            
            plt.xlabel("Bond angle (°)", fontsize=14)
            plt.ylabel("Density", fontsize=14)
            plt.tick_params(axis='both', labelsize=12, length=6, width=1.5)
            plt.title(f"Bond Angle Density - {bond_type}")
            plt.tight_layout()
            plt.savefig(os.path.join(output_dir, f"8_Angle_Distribution_{bond_type}.png"), dpi=300)
            plt.close()

    def _plot_convergence_history(self, output_dir):
        """
        Generates a detailed convergence profile illustrating the sequential 
        evolution of the refinement residual (Rw) across global iterations, 
        differentiated by temperature.
        """
        plt.figure(figsize=(10, 6))
        temps = sorted(self.rw_histories.keys())
        if not temps:
            return

        norm = plt.Normalize(min(temps), max(temps))
        cmap = plt.cm.viridis_r
        
        for t in temps:
            history = self.rw_histories[t]
            if not history.empty:
                plt.plot(history['Global_Iteration'], history['Rw'], 
                         color=cmap(norm(t)), alpha=0.6, linewidth=1)
        
        sm = plt.cm.ScalarMappable(cmap=cmap, norm=norm)
        sm.set_array([])
        cbar = plt.colorbar(sm)
        cbar.set_label('Temperature (°C)')
        
        plt.yscale('log')
        plt.title("Refinement Convergence Profiles (Logarithmic Scale)")
        plt.xlabel("Cumulative Iteration Step")
        plt.ylabel("Rw")
        plt.grid(True, which="both", alpha=0.2)
        plt.savefig(os.path.join(output_dir, "4_Convergence_Traces.png"), dpi=300)
        plt.close()

    def _plot_forensics_evolution(self, output_dir):
        """
        Visualises the statistical density distribution of specified bond lengths 
        across the experimental series, meticulously categorised by local atomic 
        connectivity configurations.
        """
        if not self.detailed_forensics_data:
            return

        df_bonds = pd.DataFrame(self.detailed_forensics_data).sort_values('Temperature')
        
        plt.figure(figsize=(14, 8))
        sns.violinplot(data=df_bonds, x='Temperature', y='Bond_Length', hue='Connectivity', 
                       inner=None, palette="muted", split=False, cut=0)
        sns.stripplot(data=df_bonds, x='Temperature', y='Bond_Length', hue='Connectivity',
                      dodge=True, jitter=True, size=2, alpha=0.5, palette="dark:black")
        plt.axhline(1.80, color='red', linestyle='--', linewidth=2, label="Anomalous Threshold (1.8 Å)")
        
        plt.title("Statistical Evolution of V-O Bond Length Distributions by Connectivity Topology")
        plt.xlabel("Temperature (°C)")
        plt.ylabel("Bond Length (Å)")
        plt.legend(bbox_to_anchor=(1.05, 1), loc='upper left')
        plt.grid(True, axis='y', alpha=0.3)
        plt.tight_layout()
        plt.savefig(os.path.join(output_dir, "5_Bond_Evolution_Violin.png"), dpi=300)
        plt.close()

    def _plot_params_evolution(self, output_dir, df):
        """
        Generates a multi-panel grid charting the progressive evolution of targeted 
        refinement variables against temperature. Dynamically calibrates the y-axis 
        to ensure data trends remain prominent, disregarding excessive calculated 
        uncertainties.
        """
        params_to_plot = self.target_params
        
        fig, axes = plt.subplots(2, 3, figsize=(18, 10))
        axes = axes.flatten()
        
        for i, param in enumerate(params_to_plot):
            ax = axes[i]
            
            if param in df.columns:
                x = df['Temperature']
                y = df[param]
                y_err = df[f"{param}_err"]
                
                ax.errorbar(x, y, yerr=y_err, fmt='-o', capsize=2, markersize=5, 
                            color='darkcyan', ecolor='gray', alpha=0.8)
                
                ax.set_title(param)
                ax.set_xlabel('Temperature (°C)')
                ax.set_ylabel('Refined Value')
                
                valid_y = y[~np.isnan(y)]
                if len(valid_y) > 0:
                    y_min, y_max = np.min(valid_y), np.max(valid_y)
                    
                    if y_min == y_max:
                        margin = abs(y_min) * 0.1 if y_min != 0 else 0.1
                    else:
                        margin = (y_max - y_min) * 0.1
                        
                    ax.set_ylim(y_min - margin, y_max + margin)
                
                ax.grid(True, alpha=0.3)
            else:
                ax.text(0.5, 0.5, f"Parameter '{param}' Unidentified", ha='center')

        plt.tight_layout()
        plt.suptitle("Refinement Variable Evolution Sequences (Auto-Scaled Y-Axes)", y=1.02, fontsize=16)
        plt.savefig(os.path.join(output_dir, "6_Parameters_Evolution.png"), dpi=300, bbox_inches='tight')
        plt.close()

# =============================================================================
# MAIN EXECUTION PROTOCOL
# =============================================================================
if __name__ == "__main__":
    
    # Define the primary directory pathway containing the sequential refinement subdirectories.
    fits_root = "fits/NewResults_Feb2026/Fit_ContinousSeries/ZirconiumVanadate_Refinement09012026_FreshStartIso100CPhaseTransition"
    
    if not os.path.exists(fits_root):
        print(f"[WARN] The defined root directory '{fits_root}' was not located. Defaulting to the current working directory.")
        fits_root = "." 

    # Initialise the central analysis aggregator using the validated configuration.
    aggregator = ResultsAggregator(fits_root, project_config)
    
    # Execute the primary data extraction sweep.
    aggregator.scan_and_extract()
    
    # Generate the comprehensive suite of visual summaries within the target data directory.
    report_dir = os.path.join(fits_root, "Analysis_Report_Summary")
    aggregator.plot_overview(output_dir=report_dir)

